### ISSUE TITLE
Frequent blank transcripts

### ISSUE THREAD

**Issue by joshua-wyatt** [awslabs/live-streaming-with-automated-multi-language-subtitling#13]
I'm testing a modified version of this solution, with the stock SuperJAR provided here.  I'm seeing a decent amount of blank text coming back from Transcribe, though -- probably 5-10% of requests.  
Logging out the response object shows that the Java Lambda is returning properly (and the execution times are in line with successful ones), it's just blank data:
`{'words': [], 'transcript': ''}`

Is this just quirkiness of Transcribe and to be expected, or am I running into a problem with limits, etc?  I do see the rate of blanks rise when I run multiple streams simultaneously.  I'm using 6-second segments, so it's being asked to process 10 segments/min per stream.

**Comment by EddieGoynesAmazon** [comment]
Hi Joshua. 
Possibly Transcribe didn't see spoken text during that 6 second segment. To rule out any throttling you can try to deploy in a different region that doesn't have any Transcribe use, since the throttling is region based. The limits are pretty low at 10 concurrent requests (Streams), those can be increased with a ticket through the console.

**Comment by joshua-wyatt** [comment]
Thanks, Eddie. 
I can confirm that the submitted segments do contain audio; the loop I'm playing back for testing is a pretty clean studio interview, and a chunk that may be missed on one loop will come out with text on the next loop several minutes later.

Does each request to Transcribe (ie, each 6-second segment) count as a Stream, or is it some lower number based on how many segments are being worked on at the same time? (ie, if processing of two segments overlap, it would count as 2, but if each segment finishes prior to the next one beginning, it's seen as just 1 Stream)?

Not knowing how the internals of the Java portion work, I'm also curious how the short segments lengths interact with the Transcribe billing apparatus -- the minimum charge is noted as 15 seconds.  Will each of my 6-second segments be billed for 15 seconds, or are they somehow combined and I will be billed based on the overall runtime of the live broadcast?

**Comment by EddieGoynesAmazon** [comment]
We have an update coming soon that changes to use long running Transcribe. Since the billing changed to 15 seconds, each 6 second segment is billed as 15 seconds. This new implementation has a long running stream to Transcribe using ECS.
