### ISSUE TITLE
speaker identification

### ISSUE THREAD

**Issue by balavenkatesh3322** [awslabs/live-streaming-with-automated-multi-language-subtitling#15]
Will you support the speaker identification feature?

**Comment by EddieGoynesAmazon** [comment]
Streaming Transcription does not have speaker identification today. When that feature is available then it will make it into this solution. They do have it for the audio file processing service, but not the streaming transcription SDK. https://docs.aws.amazon.com/transcribe/latest/dg/how-diarization.html
