### ISSUE TITLE
Transcribing existing rtmp stream 

### ISSUE THREAD

**Issue by jinyeng** [awslabs/live-streaming-with-automated-multi-language-subtitling#19]
We do have an rtmp stream existing on our own datacenter which is public. What is best way to transctibe it without extracting them on aws S3 bucket and repackaging ? 

We want to leverage only caption abilities of aws transcode.

**Comment by EddieGoynesAmazon** [comment]
Hi there @jinyeng 

If you able to run code in your datacenter you can have a script running that takes the RTMP stream and sends it to Amazon Transcribe Streaming using a Web-socket. An example is here at this blog post. https://aws.amazon.com/blogs/aws/amazon-transcribe-streaming-now-supports-websockets/

Amazon Transcribe will give you back the spoken text in the stream. You will have to use an encoding program to embed the captions back into your RTMP stream. Let me know if you have more questions.
