### ISSUE TITLE
Real-time subtitling for an audio-only output

### ISSUE THREAD

**Issue by nextlink-yik** [awslabs/live-streaming-with-automated-multi-language-subtitling#21]
We are creating a live streaming with multiple audio track selections and real-time subtitling.
When we try to modify captionlambda to make use of a specific audio track for real-time subtitling, we notice that the command below is unable to return `start_pts` for an audio-only output with aac format.
https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/blob/8bcc5268b7ec77c776e000ac86ce9b2ec751eb8a/source/captionlambda/lambda_function.py#L289

For a .ts output file, the output of the ffprobe command:
```
$ ./ffprobe -v quiet -select_streams v:0 -show_entries format=duration:stream=start_pts -of default=noprint_wrappers=1 channel_416x234_200k_00361.ts 
start_pts=194801400
start_pts=194801400
duration=6.006000
```

For a .aac output file, the output of the ffprobe command:
```
$ ./ffprobe -v quiet -select_streams v:0 -show_entries format=duration:stream=start_pts -of default=noprint_wrappers=1 channeleng_00015.aac 
duration=6.207656
```

Is there any way to get `start_pts` out of a .aac output file? Can we apply configuration in AWS Elemental MediaLive console to keep outputing .ts format with `start_pts` instead of outputing .aac file?
Thanks.

**Comment by nextlink-yik** [comment]
Just figure it out that files with audio stream only should be handled with `-select_streams a` parameter and the output is as follows:
```
$ ./ffprobe -v quiet -select_streams a -show_entries format=duration:stream=start_pts -of default=noprint_wrappers=1 channeleng_00015.aac 
start_pts=N/A
duration=6.207656
```
Unfortunately, the `start_pts` is returned as N/A... Even `-select_streams a:0` returns the same result.

FYI, this is the ffprobe result:
```
$ ./ffprobe channeleng_00015.aac 
ffprobe version 4.0.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[aac @ 0x5acb300] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'channeleng_00015.aac':
  Metadata:
    id3v2_priv.com.elementaltechnologies.timestamp.utc: 2020-06-16T07:36:32Z
    id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00v\xa1`
  Duration: 00:00:06.21, bitrate: 186 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 186 kb/s
```

**Comment by EddieGoynesAmazon** [comment]
AAC file format does not have PTS values, PTS is part of the (.TS) MPEG transport stream to achieve synchronization of subtitles in MediaPackage. 

You should change the MediaLive settings to have the audio in with the video in the TS format. Which ever audio is in the main stream will be the one getting captioning from Transcribe. 

https://en.wikipedia.org/wiki/Presentation_timestamp
