### ISSUE TITLE
How would I translate audio and not just subtitles to multiple languages?

### ISSUE THREAD

**Issue by kirankc** [awslabs/live-streaming-with-automated-multi-language-subtitling#22]
The video shows that you can perform audio translation too and not just sub-titling. Any guidance on how to go about doing that?
https://youtu.be/2_iHbiMDmx0?t=195

**Comment by pcolmer** [comment]
From watching that video, it seems like you take the translated subtitles and then pass them through Polly (https://aws.amazon.com/polly/) in order to get an audio file. I suspect (given the lack of replies to this issue) that the functionality isn't built into this specific repo.

**Comment by tomgilman** [comment]
My apologies for the delay.  Its true, Polly isn't in this software project.  The YouTube video showed what was possible to do.  As of today, we don't have plans to add support for Polly into this project.
