### ISSUE TITLE
Add new parameter to work with all languages supported by Amazon Transcribe

### ISSUE THREAD

**Issue by alexcasalboni** [awslabs/live-streaming-with-automated-multi-language-subtitling#26]
Amazon Transcribe supports real-time transcription for many languages other than English such as German, Italian, Portuguese, Spanish, and Japanese. 

This could become an additional input parameter (instead of [hard-coding](https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/blob/master/source/transcribelambda/gradle/src/main/java/com/amazonaws/transcribestreaming/cli/TranscribeStreamingDemoApp.java#L199) the source language in the Java function).

**Comment by EddieGoynesAmazon** [comment]
This feature is getting worked on for the next update.

**Comment by EddieGoynesAmazon** [comment]
Added in V2.0.0 release.
