### ISSUE TITLE
Can this solution be used for VOD?

### ISSUE THREAD

**Issue by russliu270** [awslabs/live-streaming-with-automated-multi-language-subtitling#27]
deployed this solution and it works like a charm!

is there a similar solution or can this solution be modified to do the same transcribe, translate and caption flow for VOD replays?

**Comment by EddieGoynesAmazon** [comment]
I added some links to your other issue. Happy holidays! 
https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/issues/28
