### ISSUE TITLE
VOD replay subtile

### ISSUE THREAD

**Issue by russliu270** [awslabs/live-streaming-with-automated-multi-language-subtitling#28]
deployed this solution and it works like a charm for live streaming.

is there a similar solution or can this solution be modified to do the same transcribe, translate and caption flow for VOD replays?

**Comment by EddieGoynesAmazon** [comment]
Hi, 

Take a look at this project for adding subtitles from AWS Transcribe to MOV or MP4 files. If you have VOD archive files this project will help you produce caption output files. This will produce the highest quality of output caption files.
https://github.com/awslabs/aws-content-analysis

Additionally if you run a live event through this implementation you can setup a Harvest Job in MediaPackage to save the event that you just played through this live streaming with automated multi language subtitling implementation. 
https://docs.aws.amazon.com/mediapackage/latest/ug/harvest-jobs.html

The AWS MediaPackage service also has a cool feature that allows for time shifted viewing. Here is the link for that. 
https://docs.aws.amazon.com/mediapackage/latest/ug/time-shifted.html

**Comment by russliu270** [comment]
Thank you!

**Comment by EddieGoynesAmazon** [comment]
You are welcome. Please let me know if you any other questions!
