### ISSUE TITLE
How do I use this with youtube live streaming?

### ISSUE THREAD

**Issue by wsolorza** [awslabs/live-streaming-with-automated-multi-language-subtitling#29]
How do I use this with youtube live streaming?

**Comment by EddieGoynesAmazon** [comment]
Hi there. So this solution gives an AWS MediaPackage HLS endpoint as an output. This is what you would put into a Javascript video player to play back your video stream with captions. Youtube takes an RTMP stream as ingest. This solution does not have the ability to embed subtitles into the RTMP stream. 

We currently do not have the ability to output RTMP with subtitles embedded with this project. Currently you would have to research how to use an open source tool to take the HLS output stream and convert it to RTMP with captions embedded. The FFMPEG tool I believe can do this. Thank you for the question, please reopen this issue if you have more questions.
