### ISSUE TITLE
Add addtional languages on the Cloud Formation template

### ISSUE THREAD

**Issue by MGSAWS** [awslabs/live-streaming-with-automated-multi-language-subtitling#31]
Amazon Transcribe has more subtitles than the ones presented on the cloud formation stack configuration. It would be good to add them so they can be selected while deploying the solutions. Screenshot of the possible languages attached:
<img width="832" alt="Screenshot 2021-03-17 at 09 25 22" src="https://user-images.githubusercontent.com/80712599/111442040-398d9400-8708-11eb-942b-424aea1bf618.png">
For example I would like to use es-es rather than es-US

**Comment by EddieGoynesAmazon** [comment]
Hello there. Thank you for reaching out. We are using the Amazon Transcribe Streaming feature in Amazon Transcribe. It looks like in the documentation it still is not supporting en-US. It looks like the documentation has moved around some, I will update the link to the languages in the ReadME.

Let me know if you have more questions. It looks like the Amazon Transcribe Streaming functionality supports a few less languages.

https://docs.aws.amazon.com/transcribe/latest/dg/what-is-transcribe.html
![image](https://user-images.githubusercontent.com/40248820/111501499-460eee00-8702-11eb-852e-0885f5df4d7d.png)
