### ISSUE TITLE
Build and deploy error

### ISSUE THREAD

**Issue by AustinSnow** [awslabs/live-streaming-with-automated-multi-language-subtitling#45]
Hello AwsLabs,
I'm trying to build and deploy as shown in the readme and I'm getting the following error during the `CustomDeployLambdaEdge` stack deployment:

`An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist`

The bucket I'm using when running the `build-s3-dist.sh` does exist.

Thanks
Austin

**Comment by thatdoogieguy** [comment]
@AustinSnow @gando001 i've been experiencing the same issues you have. I also get the same issue when trying to modify basically anything to do with the template as it'll throw a bucket error either in build, or on deploy when it says the S3 bucket doesn't pass pattern validation.

Word of caution, don't try and work around the problem by using V1.0.3, there is an undocumented but well known to AWS issue with these older releases that will cause issues in playback streaming.

**Comment by AustinSnow** [comment]
Thanks for the info thatdoogieguy. 

After rereading the readme file, I was able to figure it out my issue.  The bucket name MUST have `-us-east-1` at the end of the name.  And you don't include  `-us-east-1` when running `build-s3-dist.sh`

The template will append `-us-east-1` to the bucket [here](https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/blob/6d3409db0dd11d0267468053f2467432a0065364/deployment/live-streaming-with-automated-multi-language-subtitling.template#L1175).
