### ISSUE TITLE
Your access has been denied by S3 when creating a custom build

### ISSUE THREAD

**Issue by x925x** [awslabs/live-streaming-with-automated-multi-language-subtitling#48]
Hello,

I wanted to change the encoding profiles that are created by the stack, so I've followed the instructions to create a custom build.

I've changed the live-streaming-with-automated-multi-language-subtitling/source/customresources/custom-resource-py/encoding-profiles/medialive-1080p30-settings.json file, and followed all the steps in the "Creating a custom build
" part of the README.md without issues, but when I try to create the stack, I get the following error in the "CustomDeployLambdaEdge" part of the process:
Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/06/21/[$LATEST]01e630023465474eb18e0078bd42df41 (RequestId: aced655b-4047-48be-a49c-b5ee9ebf5d7d)

Looking on the CloudWatch, I can see this issue:
An error occurred (AccessDeniedException) when calling the CreateFunction operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for custom-live-subtitling-us-east-1/live-streaming-with-automated-multi-language-subtitling/v2.0.0/lambdaedge.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied.

But I'm able to access the lambdaedge.zip file from anywhere, and I can see that it has public read access enabled.

I even tried to use a role with Admin access to create the Stack, but the error persist. Do you have any idea what the issue might be?

**Comment by eggoynes** [comment]
Hello @x925x

Is the bucket custom-live-subtitling-us-east-1 in the AWS Virginia (us-east-1) region? 

The lambdaedge.zip function has to be deployed in the us-east-region, and the behavior of Lambda is that it has to use the source zip file from the same region as it is deployed. (In this case us-east-1)

I will add this extra information into the readme. 
Going to reproduce this on my end. Closing out for the backlog.
