### ISSUE TITLE
Support for multiple pipelines?

### ISSUE THREAD

**Issue by taschmidt** [awslabs/live-streaming-with-automated-multi-language-subtitling#50]
We had this solution working until we tried to go to prod where we have MediaLive channels with multiple pipelines. We hacked the HLS output to just go straight to the MediaPackage input #2 (unlike the first one which goes through CloudFront to MP input #1). That appeared to work until we tried failing over from input #1 to #2. When we shut off streaming to input #1 it didn't fail over like we expected it would (and what it does when just streaming right to MediaPackage like we used to). Any ideas on how to handle this situation?

**Comment by eggoynes** [comment]
Hi @taschmidt

Glad to hear from you. Just read through your post, and how you are putting this in production with dual pipeline MediaLive with MediaPackage. I think I know exactly what setting you have to change. Since this project is setup for the Single Pipeline AWS MediaLive this setting is not set. 

What you have to set to make failover work normally is in the AWS MediaLive make sure on the HLS output **Pause Output** is set for HLS segments when Input video loss occurs. 
![image](https://user-images.githubusercontent.com/40248820/129269022-cc113c7b-668d-4464-a7ee-9aeb925365be.png)


Shoot me an email, I would be happy to jump on a Video Call with you. My email is just my GitHub username + amazon.com

**Comment by taschmidt** [comment]
Cool, thanks @eggoynes. We'll test that out early next week and let you know!

**Comment by taschmidt** [comment]
So we encountered some problems with this solution. If our editors switch off the stream before the scheduled end of the event, it causes the MediaPackage harvest job to fail because we use those same timecodes in the harvest jobs. Any ideas there?

**Comment by eggoynes** [comment]
I send a message over to the MediaPackage team. I should hear back soon about procedure harvesting jobs if the MediaLive event ends before the scheduled time.

**Comment by eggoynes** [comment]
Hi Tim. The MediaPackage CloudWatch logs show when the channel stopped getting IngressBytes, that is how we can tell when the MediaLive was stopped. Can you send me an email with your channel ARN? Thanks

**Comment by taschmidt** [comment]
Yep, the ARN for the MediaPackage channel is `arn:aws:mediapackage:us-east-1:326613286907:channels/2bfc9941b02d4515b920163749979c58`.

I was incorrect in my previous message, the MediaPackage harvest job did succeed but we ended up with an invalid m3u8 file. See the generated manifest [here](https://m.wsj.net/video-live-qa/20210824/2c677ddd-75ae-43cf-8bd8-e4c3460d85b4_copy/hls/index_20.m3u8). Notice it doesn't end with a **#EXT-X-ENDLIST** tag like the manifest from our previous job [here](https://m.wsj.net/video-live-qa/20210819/b723962b-102c-4076-8cfd-ed28b571aa6e/hls/index_20.m3u8).

**Comment by eggoynes** [comment]
Hi @taschmidt
Try making the harvest job again, and use the time that the harvest job ends as the ending timecode.

The manifest that is generated gets to this point. I am thinking that maybe if the timecode at this point is chosen as the end-time then the **#EXT-X-ENDLIST** tag will show up. I have not made VOD harvest enough to know for sure.
index_20_60958.ts

**Comment by eggoynes** [comment]
That makes sense. I asked if a feature such as this in on the MediaPackage roadmap. If you reach out to your TAM they have more power than I to get new features into the product. I have asked if they have a workaround to add in #EXT-X-ENDLIST. 

I was looking to see if there is a way to add it in after the fact, I have emailed them asking that as well.

**Comment by taschmidt** [comment]
FYI, I did do what you suggested and reached out to our TAM who requested the feature from the MediaPackage team.

**Comment by eggoynes** [comment]
That is great to hear @taschmidt 

This feature will benefit many AWS MediaPackage customers. I am glad you found it. It makes sense that an #EXT-X-ENDLIST should be added to all VOD assets. Especially when players use that to play back in VOD mode. Closing this for now.
