### ISSUE TITLE
VTT end time Timecode isn't inserted properly since few days ago

### ISSUE THREAD

**Issue by flvlef** [awslabs/live-streaming-with-automated-multi-language-subtitling#52]
Hi,
We are intensively fine tuning this repo.
Since two days the MediaPackage timecode handling is different. We tried this original code and we experience the same result.

On this issue you explained what MediaPackage was doing with TCs https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/issues/42

But the output we get now is something like

```
00:00:01.000 --> 1000000:00:03.300
What was his name again?
```

Instead of `_end_PTS_Timestamp_in_Video_TS_File_` as mention on the issue 42

We tried different values on `source/lambdafunctions/lambdaedge/lambda_function.py` file like

- removing timcodes
- removing endtime
- change endtime to 00:00:00.000, 00:00:00.001, 23:59:59.999

cc
@x925x @diogofirmino

**Comment by eggoynes** [comment]
Thank you for the feedback. We are taking a look at this.

**Comment by innomanik** [comment]
It seems like I have also started to experience something like this now.
![Screenshot 2021-08-25 143148](https://user-images.githubusercontent.com/7654961/130769477-cfe6534f-7146-420c-aed5-22b0d52f1040.png)

**Comment by eggoynes** [comment]
Hi there. This was resolved a couple weeks ago in the AWS MediaPackage service. Please reopen if you have any additional questions. Thank you.
